const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let selectedDay=+(localStorage.getItem('eurotrip-day')||1);
const maps=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const mapEmbed=q=>'https://www.google.com/maps?q='+encodeURIComponent(q)+'&output=embed';
function iconFor(n){if(/早餐|午餐|晚餐|Brunch|咖啡/.test(n))return'☕';if(/睡眠/.test(n))return'☾';if(/→|TGV|AVE|直飞/.test(n))return'→';if(/起床|退房|入住/.test(n))return'⌂';return'●'}
function rowHref(x,n){if(/早餐/.test(n))return maps('breakfast '+x.q);if(/午餐/.test(n))return maps('lunch '+x.q);if(/晚餐|Brunch|咖啡/.test(n))return maps(x.food);if(/→|TGV|AVE|直飞|前往/.test(n))return x.transport;return maps(n)}
function timeline(x){return `<div class="timeline">${x.items.map(([t,n])=>`<div class="trow"><span class="time">${t}</span><span class="ico">${iconFor(n)}</span><span><b>${n}</b></span><a class="rowlink" href="${rowHref(x,n)}" target="_blank" rel="noopener">${/早餐|午餐|晚餐|Brunch|咖啡/.test(n)?'找餐厅':(/→|TGV|AVE|直飞|前往/.test(n)?'交通':'地图')}</a></div>`).join('')}</div>`}
function actions(x){return `<div class="action-strip"><a class="action primary" href="${maps(x.q)}" target="_blank">🗺 地图</a><a class="action" href="${maps(x.food)}" target="_blank">🍽 餐饮</a><a class="action" href="${maps(x.hotelq)}" target="_blank">🛏 住宿</a><a class="action" href="${x.transport}" target="_blank">🚆 交通</a><a class="action accent" href="${x.official}" target="_blank">↗ 官网 / 预约</a></div>`}
function go(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));location.hash=v;render(v);scrollTo({top:0,behavior:'smooth'})}$$('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));
function renderOverview(){$('#overview').innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">24 DEC 2026 → 09 JAN 2027</div><h1>15天，四个国家。</h1><p>恢复旅行途中最重要的执行入口：地图、餐饮、住宿、交通与官网/预约全部可以一键打开，同时维持五入口的精简结构。</p><div class="chips">${COUNTRIES.map(c=>`<span class="chip">${c[0]} · ${c[1]}</span>`).join('')}</div></div><div class="visual"><svg viewBox="0 0 520 260"><path d="M65 180 C130 125,145 185,205 135 S285 70,325 120 S395 210,455 135" fill="none" stroke="#f1d7cf" stroke-width="5" stroke-linecap="round" stroke-dasharray="5 10"/><g fill="#fffdf9" stroke="#d96f55" stroke-width="5"><circle cx="65" cy="180" r="11"/><circle cx="205" cy="135" r="11"/><circle cx="325" cy="120" r="11"/><circle cx="455" cy="135" r="11"/></g><g fill="#fffdf9" font-size="14"><text x="45" y="215">Italy</text><text x="174" y="105">Switzerland</text><text x="305" y="88">France</text><text x="438" y="170">Spain</text></g></svg></div></section><h2>国家路线</h2><div class="country-grid">${COUNTRIES.map(c=>`<div class="country-card"><h3>${c[0]}</h3><p>${c[1]}<br>${c[2]}</p></div>`).join('')}</div><h2>15天总览</h2><div class="list">${DAYS.map(x=>`<div class="row"><span class="num">DAY ${x.d}<br>${x.date}</span><span><b>${x.title}</b><small>${x.hotel}</small></span><button class="small-btn" data-open-day="${x.d}">打开</button></div>`).join('')}</div>`;$$('[data-open-day]').forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.openDay;localStorage.setItem('eurotrip-day',selectedDay);go('schedule')})}
function isDone(d,i){return localStorage.getItem(`done-${d}-${i}`)==='1'}
function serviceGrid(x){return `<div class="service-grid"><div class="service"><h3>🍽 今日餐饮</h3><div class="service-line"><span>早餐</span><a href="${maps('breakfast '+x.q)}" target="_blank">附近搜索 ↗</a></div><div class="service-line"><span>午餐</span><a href="${maps('lunch '+x.q)}" target="_blank">附近搜索 ↗</a></div><div class="service-line"><span>晚餐</span><a href="${maps(x.food)}" target="_blank">附近搜索 ↗</a></div></div><div class="service"><h3>🛏 住宿与交通</h3><div class="service-line"><span>${x.hotel}</span><a href="${maps(x.hotelq)}" target="_blank">住宿区域 ↗</a></div><div class="service-line"><span>当日主要交通</span><a href="${x.transport}" target="_blank">官网 / 导航 ↗</a></div><div class="service-line"><span>关键官网</span><a href="${x.official}" target="_blank">打开 ↗</a></div></div></div>`}
function renderToday(){let d=+(localStorage.getItem('eurotrip-today')||1),x=DAYS.find(z=>z.d===d)||DAYS[0],ni=x.stops.findIndex((s,i)=>!isDone(x.d,i));if(ni<0)ni=x.stops.length-1;let next=x.stops[ni]||x.title;$('#today').innerHTML=`<div class="today-head"><div><div class="eyebrow">TODAY</div><h1 class="page-title">今天只看这一页。</h1></div><select id="daySelect">${DAYS.map(z=>`<option value="${z.d}" ${z.d===x.d?'selected':''}>Day ${z.d} · ${z.date} · ${z.title}</option>`).join('')}</select></div><div class="next"><small>NEXT · DAY ${x.d}</small><strong>${next}</strong><p>${x.hotel}</p></div>${actions(x)}${timeline(x)}<div class="checks">${x.stops.map((s,i)=>`<button class="check ${isDone(x.d,i)?'done':''}" data-check="${i}" data-map="${s}">${isDone(x.d,i)?'✓':'○'} ${s}</button>`).join('')}</div>${serviceGrid(x)}<div class="mapbox"><iframe loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="${mapEmbed(x.q)}"></iframe></div>`;$('#daySelect').onchange=e=>{localStorage.setItem('eurotrip-today',e.target.value);renderToday()};$$('#today [data-check]').forEach(b=>{b.onclick=e=>{if(e.altKey||e.metaKey)return;let k=`done-${x.d}-${b.dataset.check}`;localStorage.setItem(k,localStorage.getItem(k)==='1'?'0':'1');renderToday()};b.ondblclick=()=>open(maps(b.dataset.map),'_blank')})}
function renderSchedule(){let x=DAYS.find(z=>z.d===selectedDay)||DAYS[0];$('#schedule').innerHTML=`<div class="eyebrow">ITINERARY</div><h1 class="page-title">15天行程</h1><div class="day-tabs">${DAYS.map(z=>`<button class="daytab ${z.d===x.d?'active':''}" data-day="${z.d}">Day ${z.d} · ${z.date}</button>`).join('')}</div><h2>${x.title}</h2>${actions(x)}<div class="glance"><div class="card"><small>Hotel</small><b>${x.hotel}</b><a class="small-btn" href="${maps(x.hotelq)}" target="_blank">住宿地图</a></div><div class="card"><small>Meals</small><b>早餐 / 午餐 / 晚餐</b><a class="small-btn" href="${maps(x.food)}" target="_blank">附近餐饮</a></div><div class="card"><small>Transport</small><b>当日主要交通</b><a class="small-btn" href="${x.transport}" target="_blank">交通官网</a></div><div class="card"><small>Official</small><b>景点 / 预约</b><a class="small-btn" href="${x.official}" target="_blank">打开官网</a></div></div>${timeline(x)}${serviceGrid(x)}<div class="mapbox"><iframe loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="${mapEmbed(x.q)}"></iframe></div><details class="options"><summary>备选景点 (${x.opt.length}项，默认不进入主计划)</summary>${x.opt.map((o,i)=>{let k=`watch-${x.d}-${i}`,on=localStorage.getItem(k)==='1';return`<div class="opt"><b>${o}</b><p>仅作为替换/观察项。</p><a class="small-btn" href="${maps(o)}" target="_blank">地图</a> <button class="watch ${on?'on':''}" data-watch="${i}">${on?'★ 已关注':'☆ 关注'}</button></div>`}).join('')}</details>`;$$('#schedule [data-day]').forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.day;localStorage.setItem('eurotrip-day',selectedDay);renderSchedule()});$$('#schedule [data-watch]').forEach(b=>b.onclick=()=>{let k=`watch-${x.d}-${b.dataset.watch}`;localStorage.setItem(k,localStorage.getItem(k)==='1'?'0':'1');renderSchedule()})}
function renderDesk(){const stays=[...new Map(DAYS.map(x=>[x.hotel,x])).values()];const moves=DAYS.filter(x=>/→|TGV|AVE|直飞/.test(x.title));$('#desk').innerHTML=`<div class="eyebrow">TRIP DESK</div><h1 class="page-title">预约、住宿、交通与常用 App。</h1><div class="desk-tabs"><button class="active" data-tab="book">预约</button><button data-tab="stay">住宿</button><button data-tab="move">交通</button><button data-tab="apps">App / 网站</button></div><section class="desk-panel active" id="panel-book"><div class="list">${BOOKINGS.map(x=>`<div class="manage-row"><span><b>${x[1]}</b><small>${x[0]}</small></span><a class="small-btn" href="${x[2]}" target="_blank">官网预约</a></div>`).join('')}</div></section><section class="desk-panel" id="panel-stay"><div class="list">${stays.map(x=>`<div class="manage-row"><span><b>${x.hotel}</b><small>Google Maps / 酒店区域</small></span><a class="small-btn" href="${maps(x.hotelq)}" target="_blank">打开住宿</a></div>`).join('')}</div></section><section class="desk-panel" id="panel-move"><div class="list">${moves.map(x=>`<div class="manage-row"><span><b>Day ${x.d} · ${x.title}</b><small>${x.date} · ${x.country}</small></span><a class="small-btn" href="${x.transport}" target="_blank">官网 / App</a></div>`).join('')}</div></section><section class="desk-panel" id="panel-apps"><div class="app-grid">${APPS.map(a=>`<div class="app-card"><small>${a[0]}</small><b>${a[1]}</b><p>手机安装对应 App 时，Universal Link 通常会优先唤起 App；否则打开网页。</p><a class="small-btn" href="${a[2]}" target="_blank">打开</a></div>`).join('')}</div></section>`;$$('#desk [data-tab]').forEach(b=>b.onclick=()=>{$$('#desk [data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.desk-panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+b.dataset.tab))})}
function showModal(t,h){$('#modalBody').innerHTML=`<h2>${t}</h2>${h}`;$('#modal').classList.add('show')}
function installHelp(){showModal('安装 EuroTrip','<p>iPhone：Safari → 分享 → 添加到主屏幕。</p><p>Android：Chrome → 菜单 → 安装应用 / 添加到主屏幕。</p>')}
function renderMore(){$('#more').innerHTML=`<div class="eyebrow">MORE</div><h1 class="page-title">低频功能</h1><div class="notice">护照、签证、真实机票和订单不要上传到公开 GitHub Pages。地图、餐饮、住宿、交通和官网入口已经放回 Today、行程与 Trip Desk。</div><div class="more-grid" style="margin-top:12px"><button class="tile" data-info="check"><b>出发清单</b><p>证件、衣物、行李</p></button><button class="tile" data-info="budget"><b>预算</b><p>预算与支出</p></button><button class="tile" data-info="split"><b>三人分账</b><p>同行费用结算</p></button><button class="tile" data-info="install"><b>安装到手机</b><p>iPhone / Android</p></button><button class="tile" data-info="sync"><b>状态与备份</b><p>本机 LocalStorage</p></button></div>`;$$('#more [data-info]').forEach(b=>b.onclick=()=>{if(b.dataset.info==='install')return installHelp();let m={check:['出发清单','<p>护照、签证、保险、银行卡、转换插头、充电宝、冬季保暖层、常用药、全部电子票。</p>'],budget:['预算','<p>目标预算约 ¥20,000–25,000/人；圣诞、跨年与瑞士冬季住宿是主要波动项。</p>'],split:['三人分账','<p>建议统一付款人并每天晚间一次结算。</p>'],sync:['状态与备份','<p>Today 完成状态和备选景点关注状态保存在浏览器 LocalStorage。</p>']};showModal(...m[b.dataset.info])})}
function render(v){if(v==='overview')renderOverview();if(v==='today')renderToday();if(v==='schedule')renderSchedule();if(v==='desk')renderDesk();if(v==='more')renderMore()}
$('#closeModal').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('show')};
let installPrompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});$('#install').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else installHelp()};
function net(){let on=navigator.onLine;$('#net').textContent=on?'Online':'Offline';$('#net').style.color=on?'var(--ok)':'var(--accent)'}addEventListener('online',net);addEventListener('offline',net);net();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
let initial=(location.hash||'#overview').slice(1);if(!['overview','today','schedule','desk','more'].includes(initial))initial='overview';go(initial);